INSERT INTO ItemsType(TypeName) VALUES ('Rezistor');
INSERT INTO ItemsType(TypeName) VALUES ('Capacitor');
INSERT INTO ItemsType(TypeName) VALUES ('Diode');


INSERT INTO Unit(UnitName) VALUES ('Ω');
INSERT INTO Unit(UnitName) VALUES ('kΩ');
INSERT INTO Unit(UnitName) VALUES ('MΩ');
INSERT INTO Unit(UnitName) VALUES ('pF');
INSERT INTO Unit(UnitName) VALUES ('nF');
INSERT INTO Unit(UnitName) VALUES ('V');

INSERT INTO Items(ItemName, Count, Value, TypeID, UnitID) VALUES ('AZ23C4V7-7-F', 12, '4.7', (SELECT Id FROM ItemsType WHERE TypeName='Diode'), (SELECT Id FROM Unit WHERE UnitName='V'));
INSERT INTO Items(ItemName, Count, Value, TypeID, UnitID) VALUES ('AZ23C3V3-7-F', 10, '3.3', (SELECT Id FROM ItemsType WHERE TypeName='Diode'), (SELECT Id FROM Unit WHERE UnitName='V'));
INSERT INTO Items(ItemName, Count, Value, TypeID, UnitID) VALUES ('BZB84-B3V3,215', 56, '3.3', (SELECT Id FROM ItemsType WHERE TypeName='Diode'), (SELECT Id FROM Unit WHERE UnitName='V'));



INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('AZ23C4V7-7-F', 12, '4.7', (SELECT id FROM item_type WHERE type_name='Diode'), (SELECT id FROM unit WHERE unit_name='V'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('AZ23C3V3-7-F', 10, '3.3', (SELECT id FROM item_type WHERE type_name='Diode'), (SELECT id FROM unit WHERE unit_name='V'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('BZB84-B3V3,215', 56, '3.3', (SELECT id FROM item_type WHERE type_name='Diode'), (SELECT id FROM unit WHERE unit_name='V'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('BZB984-C12,115', 24, '12', (SELECT id FROM item_type WHERE type_name='Diode'), (SELECT id FROM unit WHERE unit_name='V'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('BZB984-C5V6,115', 10, '5.6', (SELECT id FROM item_type WHERE type_name='Diode'), (SELECT id FROM unit WHERE unit_name='V'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('BZB984-C15,115', 14, '15', (SELECT id FROM item_type WHERE type_name='Diode'), (SELECT id FROM unit WHERE unit_name='V'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('BZB84-C18,215', 24, '18', (SELECT id FROM item_type WHERE type_name='Diode'), (SELECT id FROM unit WHERE unit_name='V'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('BZB784-C5V1,115', 10, '5.1', (SELECT id FROM item_type WHERE type_name='Diode'), (SELECT id FROM unit WHERE unit_name='V'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('BZB84-B62,215', 6, '62', (SELECT id FROM item_type WHERE type_name='Diode'), (SELECT id FROM unit WHERE unit_name='V'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1R', 68, '1.0', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1R2', 10, '1.2', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1R5', 27, '1.5', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1R8', 89, '1.8', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('2R2', 241, '2.2', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('2R7', 47, '2.7', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('3R3', 54, '3.3', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('3R9', 165, '3.9', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('4R7', 84, '4.7', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('5R6', 53, '5.6', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('6R8', 63, '6.8', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('8R2', 153, '8.2', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('10R', 48, '10', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('12R', 58, '12', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('15R', 59, '15', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('18R', 41, '18', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('22R', 357, '22', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('27R', 74, '27', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('33R', 52, '33', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('39R', 412, '39', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('47R', 85, '47', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('56R', 272, '56', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('68R', 41, '68', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('82R', 67, '82', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('100R', 48, '100', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('120R', 58, '120', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('150R', 59, '150', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('180R', 41, '180', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('220R', 357, '220', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('270R', 74, '270', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('330R', 52, '330', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('390R', 412, '390', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('470R', 85, '470', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('560R', 272, '560', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('680R', 41, '680', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('820R', 67, '820', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='Ω'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1K', 68, '1.0', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1K2', 10, '1.2', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1K5', 27, '1.5', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1K8', 89, '1.8', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('2K2', 241, '2.2', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('2K7', 47, '2.7', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('3K3', 54, '3.3', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('3K9', 165, '3.9', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('4K7', 84, '4.7', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('5K6', 53, '5.6', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('6K8', 63, '6.8', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('8K2', 153, '8.2', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('10K', 48, '10', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('12K', 58, '12', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('15K', 59, '15', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('18K', 41, '18', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('22K', 357, '22', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('27K', 74, '27', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('33K', 52, '33', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('39K', 412, '39', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('47K', 85, '47', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('56K', 272, '56', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('68K', 41, '68', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('82K', 67, '82', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('100K', 48, '100', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('120K', 58, '120', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('150K', 59, '150', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('180K', 41, '180', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('220K', 357, '220', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('270K', 74, '270', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('330K', 52, '330', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('390K', 412, '390', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('470K', 85, '470', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('560K', 272, '560', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('680K', 41, '680', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('820K', 67, '820', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='kΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1M', 68, '1.0', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1M2', 10, '1.2', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1M5', 27, '1.5', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('1M8', 89, '1.8', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('2M2', 241, '2.2', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('2M7', 47, '2.7', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('3M3', 54, '3.3', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('3M9', 165, '3.9', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('4M7', 84, '4.7', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('5M6', 53, '5.6', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('6M8', 63, '6.8', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('8M2', 153, '8.2', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('10M', 48, '10', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('12M', 58, '12', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('15M', 59, '15', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('18M', 41, '18', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('22M', 357, '22', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('27M', 74, '27', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('33M', 52, '33', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('39M', 412, '39', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('47M', 85, '47', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('56M', 272, '56', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('68M', 41, '68', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('82M', 67, '82', (SELECT id FROM item_type WHERE type_name='Rezistor'), (SELECT id FROM unit WHERE unit_name='MΩ'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('100p', 147, '100', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('120p', 59, '120', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('150p', 36, '150', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('180p', 54, '180', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('220p', 18, '220', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('270p', 147, '270', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('330p', 59, '330', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('390p', 36, '390', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('470p', 54, '470', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('560p', 18, '560', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('680p', 147, '680', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('820p', 59, '820', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='pF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('100n', 147, '100', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('120n', 59, '120', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('150n', 36, '150', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('180n', 54, '180', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('220n', 18, '220', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('270n', 147, '270', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('330n', 59, '330', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('390n', 36, '390', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('470n', 54, '470', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('560n', 18, '560', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('680n', 147, '680', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
INSERT INTO item(item_name, count, value, type_id, unit_id) VALUES ('820n', 59, '820', (SELECT id FROM item_type WHERE type_name='Capacitor'), (SELECT id FROM unit WHERE unit_name='nF'));
